// Literal paths bundle the customer's supplied artwork for offline presentation.
export const assets = {
  logo: require('../../../design/prototype/assets/mockup/logo.png'),
  hero: require('../../../design/prototype/assets/mockup/hero.mp4'),
  poster: require('../../../design/prototype/assets/mockup/hero-poster.jpg'),
  blue: require('../../../design/prototype/assets/mockup/i27.jpg'),
  orange: require('../../../design/prototype/assets/mockup/bg-orange.png'),
  promo: require('../../../design/prototype/assets/mockup/i28.jpg'),
};
const products: Record<string, number> = {
  'shot.jpg': require('../../../design/prototype/assets/mockup/shot.jpg'),
  'i0.jpg': require('../../../design/prototype/assets/mockup/i0.jpg'),
  'i1.jpg': require('../../../design/prototype/assets/mockup/i1.jpg'),
  'i2.jpg': require('../../../design/prototype/assets/mockup/i2.jpg'),
  'i4.jpg': require('../../../design/prototype/assets/mockup/i4.jpg'),
  'i5.jpg': require('../../../design/prototype/assets/mockup/i5.jpg'),
  'i6.jpg': require('../../../design/prototype/assets/mockup/i6.jpg'),
  'i7.jpg': require('../../../design/prototype/assets/mockup/i7.jpg'),
  'i8.jpg': require('../../../design/prototype/assets/mockup/i8.jpg'),
  'i9.jpg': require('../../../design/prototype/assets/mockup/i9.jpg'),
  'i10.jpg': require('../../../design/prototype/assets/mockup/i10.jpg'),
  'i11.jpg': require('../../../design/prototype/assets/mockup/i11.jpg'),
  'i12.jpg': require('../../../design/prototype/assets/mockup/i12.jpg'),
  'i13.jpg': require('../../../design/prototype/assets/mockup/i13.jpg'),
  'i14.jpg': require('../../../design/prototype/assets/mockup/i14.jpg'),
  'i15.jpg': require('../../../design/prototype/assets/mockup/i15.jpg'),
  'i16.jpg': require('../../../design/prototype/assets/mockup/i16.jpg'),
  'i17.jpg': require('../../../design/prototype/assets/mockup/i17.jpg'),
  'i18.jpg': require('../../../design/prototype/assets/mockup/i18.jpg'),
  'i19.jpg': require('../../../design/prototype/assets/mockup/i19.jpg'),
  'i20.jpg': require('../../../design/prototype/assets/mockup/i20.jpg'),
  'i22.jpg': require('../../../design/prototype/assets/mockup/i22.jpg'),
  'i23.jpg': require('../../../design/prototype/assets/mockup/i23.jpg'),
};
export const productImage = (id: string) => products[id] ?? assets.logo;
