import { TestCompleteCatalogSchema } from './contracts.js';

// Synthetic editable-source fixture: design/reference-source/mobile-v2.html.txt
// SHA-256: 63ed692aaf314b3161870efb22a8680e1db679e62e7d1fd169c2626d04e42eb5
// Original descriptions, prices and per-serving nutrition are not validated for sales.
// Empty allergens mean unknown, not allergen-free. Corrupted source IDs normalized.
// Required drink/sauce counts follow written compositions; party contains no drinks.
// Paid extras start at zero; the included free drink is the default.
// This dataset is served by the API; a full back-office catalog editor remains separate.
export const testCompleteCatalog = TestCompleteCatalogSchema.parse({
  synthetic: true,
  namespace: 'pickchick-test',
  branch_id: '10000000-0000-4000-8000-000000000003',
  catalog_version: 'mockup-v0.3',
  currency: 'KZT',
  products: [
    {
      id: 'pick-combo',
      name: 'Pick Combo',
      description: '4 фингерса, 1 порция фри, 1 соус, 1 тост, 1 коулслоу и напиток на выбор.',
      category: 'Комбо',
      price_minor: '419000',
      image_id: 'i7.jpg',
      prep_required: true,
      serving_label: '520 г',
      ingredients: '4 фингерса, 1 порция фри, 1 соус, 1 тост, 1 коулслоу и напиток на выбор.',
      allergens: [],
      prep_minutes: 7,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 1240,
        protein_g: 55,
        fat_g: 72,
        carbs_g: 98,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [
        {
          id: 'drink',
          title: 'Напиток на выбор',
          min: 1,
          max: 1,
          options: [
            {
              id: 'cola-bottle',
              label: 'Coca-Cola 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 1,
            },
            {
              id: 'lemonade',
              label: 'Фирменный лимонад 0.5 л',
              price_delta_minor: '20000',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fuse-peach',
              label: 'Fuse Tea Персик 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'cola-can',
              label: 'Coca-Cola 0.5 л, банка',
              price_delta_minor: '10000',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fanta',
              label: 'Fanta 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'sprite',
              label: 'Sprite 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'cola-zero',
              label: 'Coca-Cola Zero 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'iced-tea-sweet',
              label: 'Фирменный холодный чай, сладкий',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'iced-tea-unsweet',
              label: 'Фирменный холодный чай, несладкий',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fuse-berry',
              label: 'Fuse Tea Ягода 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fuse-watermelon',
              label: 'Fuse Tea Арбуз 0.5 л',
              price_delta_minor: '0',
              available: false,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fuse-mango',
              label: 'Fuse Tea Манго-Ромашка 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'water',
              label: 'Bonaqua негазированная 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'piko',
              label: 'Piko 0.2 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'sauce',
          title: 'Соус на выбор',
          min: 1,
          max: 1,
          options: [
            {
              id: 'pick',
              label: 'Фирменный соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 1,
            },
            {
              id: 'hot',
              label: 'Острый соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'cheese',
              label: 'Heinz сырный',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'bbq',
              label: 'Heinz барбекю',
              price_delta_minor: '0',
              available: false,
              max_quantity: 1,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'extras',
          title: 'Добавить к заказу',
          min: 0,
          max: 80,
          options: [
            {
              id: 'fingers',
              label: 'Фингерс, 1 шт',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce',
              label: 'Фирменный соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-hot',
              label: 'Острый соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-cheese',
              label: 'Heinz сырный, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-bbq',
              label: 'Heinz барбекю, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'toast',
              label: 'Тост, 1 шт',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'coleslaw',
              label: 'Коулслоу, 90 г',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'wedges',
              label: 'Картофельные дольки, 90 г',
              price_delta_minor: '89000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
          ],
        },
      ],
    },
    {
      id: 'master-combo',
      name: 'Master Combo',
      description: '6 фингерсов, 1 порция фри, 2 соуса, 2 тоста, 1 коулслоу и напиток на выбор.',
      category: 'Комбо',
      price_minor: '549000',
      image_id: 'i8.jpg',
      prep_required: true,
      serving_label: '720 г',
      ingredients: '6 фингерсов, 1 порция фри, 2 соуса, 2 тоста, 1 коулслоу и напиток на выбор.',
      allergens: [],
      prep_minutes: 7,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 1780,
        protein_g: 78,
        fat_g: 104,
        carbs_g: 132,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [
        {
          id: 'drink',
          title: 'Напиток на выбор',
          min: 1,
          max: 1,
          options: [
            {
              id: 'cola-bottle',
              label: 'Coca-Cola 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 1,
            },
            {
              id: 'lemonade',
              label: 'Фирменный лимонад 0.5 л',
              price_delta_minor: '20000',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fuse-peach',
              label: 'Fuse Tea Персик 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'cola-can',
              label: 'Coca-Cola 0.5 л, банка',
              price_delta_minor: '10000',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fanta',
              label: 'Fanta 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'sprite',
              label: 'Sprite 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'cola-zero',
              label: 'Coca-Cola Zero 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'iced-tea-sweet',
              label: 'Фирменный холодный чай, сладкий',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'iced-tea-unsweet',
              label: 'Фирменный холодный чай, несладкий',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fuse-berry',
              label: 'Fuse Tea Ягода 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fuse-watermelon',
              label: 'Fuse Tea Арбуз 0.5 л',
              price_delta_minor: '0',
              available: false,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fuse-mango',
              label: 'Fuse Tea Манго-Ромашка 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'water',
              label: 'Bonaqua негазированная 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'piko',
              label: 'Piko 0.2 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'sauce',
          title: 'Соусы на выбор · 2 шт',
          min: 2,
          max: 2,
          options: [
            {
              id: 'pick',
              label: 'Фирменный соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 2,
            },
            {
              id: 'hot',
              label: 'Острый соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'cheese',
              label: 'Heinz сырный',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'bbq',
              label: 'Heinz барбекю',
              price_delta_minor: '0',
              available: false,
              max_quantity: 2,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'extras',
          title: 'Добавить к заказу',
          min: 0,
          max: 80,
          options: [
            {
              id: 'fingers',
              label: 'Фингерс, 1 шт',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce',
              label: 'Фирменный соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-hot',
              label: 'Острый соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-cheese',
              label: 'Heinz сырный, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-bbq',
              label: 'Heinz барбекю, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'toast',
              label: 'Тост, 1 шт',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'coleslaw',
              label: 'Коулслоу, 90 г',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'wedges',
              label: 'Картофельные дольки, 90 г',
              price_delta_minor: '89000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
          ],
        },
      ],
    },
    {
      id: 'burger-combo',
      name: 'Burger Combo',
      description: '1 бургер, 1 порция фри, 1 соус и напиток на выбор.',
      category: 'Комбо',
      price_minor: '379000',
      image_id: 'i9.jpg',
      prep_required: true,
      serving_label: '480 г',
      ingredients: '1 бургер, 1 порция фри, 1 соус и напиток на выбор.',
      allergens: [],
      prep_minutes: 7,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 1140,
        protein_g: 34,
        fat_g: 70,
        carbs_g: 92,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [
        {
          id: 'drink',
          title: 'Напиток на выбор',
          min: 1,
          max: 1,
          options: [
            {
              id: 'cola-bottle',
              label: 'Coca-Cola 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 1,
            },
            {
              id: 'lemonade',
              label: 'Фирменный лимонад 0.5 л',
              price_delta_minor: '20000',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fuse-peach',
              label: 'Fuse Tea Персик 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'cola-can',
              label: 'Coca-Cola 0.5 л, банка',
              price_delta_minor: '10000',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fanta',
              label: 'Fanta 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'sprite',
              label: 'Sprite 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'cola-zero',
              label: 'Coca-Cola Zero 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'iced-tea-sweet',
              label: 'Фирменный холодный чай, сладкий',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'iced-tea-unsweet',
              label: 'Фирменный холодный чай, несладкий',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fuse-berry',
              label: 'Fuse Tea Ягода 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fuse-watermelon',
              label: 'Fuse Tea Арбуз 0.5 л',
              price_delta_minor: '0',
              available: false,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fuse-mango',
              label: 'Fuse Tea Манго-Ромашка 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'water',
              label: 'Bonaqua негазированная 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'piko',
              label: 'Piko 0.2 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'sauce',
          title: 'Соус на выбор',
          min: 1,
          max: 1,
          options: [
            {
              id: 'pick',
              label: 'Фирменный соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 1,
            },
            {
              id: 'hot',
              label: 'Острый соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'cheese',
              label: 'Heinz сырный',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'bbq',
              label: 'Heinz барбекю',
              price_delta_minor: '0',
              available: false,
              max_quantity: 1,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'extras',
          title: 'Добавить к заказу',
          min: 0,
          max: 80,
          options: [
            {
              id: 'fingers',
              label: 'Фингерс, 1 шт',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce',
              label: 'Фирменный соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-hot',
              label: 'Острый соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-cheese',
              label: 'Heinz сырный, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-bbq',
              label: 'Heinz барбекю, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'toast',
              label: 'Тост, 1 шт',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'coleslaw',
              label: 'Коулслоу, 90 г',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'wedges',
              label: 'Картофельные дольки, 90 г',
              price_delta_minor: '89000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
          ],
        },
      ],
    },
    {
      id: 'solo-combo',
      name: 'Solo Combo',
      description: '3 фингерса, 1 порция фри, 1 соус, 1 тост и напиток на выбор.',
      category: 'Комбо',
      price_minor: '349000',
      image_id: 'i10.jpg',
      prep_required: true,
      serving_label: '420 г',
      ingredients: '3 фингерса, 1 порция фри, 1 соус, 1 тост и напиток на выбор.',
      allergens: [],
      prep_minutes: 7,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 1000,
        protein_g: 44,
        fat_g: 58,
        carbs_g: 82,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [
        {
          id: 'drink',
          title: 'Напиток на выбор',
          min: 1,
          max: 1,
          options: [
            {
              id: 'cola-bottle',
              label: 'Coca-Cola 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 1,
            },
            {
              id: 'lemonade',
              label: 'Фирменный лимонад 0.5 л',
              price_delta_minor: '20000',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fuse-peach',
              label: 'Fuse Tea Персик 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'cola-can',
              label: 'Coca-Cola 0.5 л, банка',
              price_delta_minor: '10000',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fanta',
              label: 'Fanta 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'sprite',
              label: 'Sprite 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'cola-zero',
              label: 'Coca-Cola Zero 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'iced-tea-sweet',
              label: 'Фирменный холодный чай, сладкий',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'iced-tea-unsweet',
              label: 'Фирменный холодный чай, несладкий',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fuse-berry',
              label: 'Fuse Tea Ягода 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fuse-watermelon',
              label: 'Fuse Tea Арбуз 0.5 л',
              price_delta_minor: '0',
              available: false,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'fuse-mango',
              label: 'Fuse Tea Манго-Ромашка 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'water',
              label: 'Bonaqua негазированная 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'piko',
              label: 'Piko 0.2 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'sauce',
          title: 'Соус на выбор',
          min: 1,
          max: 1,
          options: [
            {
              id: 'pick',
              label: 'Фирменный соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 1,
            },
            {
              id: 'hot',
              label: 'Острый соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'cheese',
              label: 'Heinz сырный',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
            },
            {
              id: 'bbq',
              label: 'Heinz барбекю',
              price_delta_minor: '0',
              available: false,
              max_quantity: 1,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'extras',
          title: 'Добавить к заказу',
          min: 0,
          max: 80,
          options: [
            {
              id: 'fingers',
              label: 'Фингерс, 1 шт',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce',
              label: 'Фирменный соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-hot',
              label: 'Острый соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-cheese',
              label: 'Heinz сырный, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-bbq',
              label: 'Heinz барбекю, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'toast',
              label: 'Тост, 1 шт',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'coleslaw',
              label: 'Коулслоу, 90 г',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'wedges',
              label: 'Картофельные дольки, 90 г',
              price_delta_minor: '89000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
          ],
        },
      ],
    },
    {
      id: 'finger-duo',
      name: 'Фингер Дуо',
      description:
        'Сытное комбо для двоих: 8 хрустящих куриных фингерсов, 1,5 порции картофельных долек, 2 фирменных соуса, 2 порции свежего коулслоу, 2 фирменных тоста, 2 напитка на выбор',
      category: 'На двоих',
      price_minor: '799000',
      image_id: 'i11.jpg',
      prep_required: true,
      serving_label: '1100 г',
      ingredients:
        'Сытное комбо для двоих: 8 хрустящих куриных фингерсов, 1,5 порции картофельных долек, 2 фирменных соуса, 2 порции свежего коулслоу, 2 фирменных тоста, 2 напитка на выбор',
      allergens: [],
      prep_minutes: 9,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 2600,
        protein_g: 104,
        fat_g: 152,
        carbs_g: 190,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [
        {
          id: 'drink',
          title: 'Напитки на выбор · 2 шт',
          min: 2,
          max: 2,
          options: [
            {
              id: 'cola-bottle',
              label: 'Coca-Cola 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 2,
            },
            {
              id: 'lemonade',
              label: 'Фирменный лимонад 0.5 л',
              price_delta_minor: '20000',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'fuse-peach',
              label: 'Fuse Tea Персик 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'cola-can',
              label: 'Coca-Cola 0.5 л, банка',
              price_delta_minor: '10000',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'fanta',
              label: 'Fanta 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'sprite',
              label: 'Sprite 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'cola-zero',
              label: 'Coca-Cola Zero 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'iced-tea-sweet',
              label: 'Фирменный холодный чай, сладкий',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'iced-tea-unsweet',
              label: 'Фирменный холодный чай, несладкий',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'fuse-berry',
              label: 'Fuse Tea Ягода 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'fuse-watermelon',
              label: 'Fuse Tea Арбуз 0.5 л',
              price_delta_minor: '0',
              available: false,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'fuse-mango',
              label: 'Fuse Tea Манго-Ромашка 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'water',
              label: 'Bonaqua негазированная 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'piko',
              label: 'Piko 0.2 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'sauce',
          title: 'Соусы на выбор · 2 шт',
          min: 2,
          max: 2,
          options: [
            {
              id: 'pick',
              label: 'Фирменный соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 2,
            },
            {
              id: 'hot',
              label: 'Острый соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'cheese',
              label: 'Heinz сырный',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'bbq',
              label: 'Heinz барбекю',
              price_delta_minor: '0',
              available: false,
              max_quantity: 2,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'extras',
          title: 'Добавить к заказу',
          min: 0,
          max: 80,
          options: [
            {
              id: 'fingers',
              label: 'Фингерс, 1 шт',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce',
              label: 'Фирменный соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-hot',
              label: 'Острый соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-cheese',
              label: 'Heinz сырный, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-bbq',
              label: 'Heinz барбекю, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'toast',
              label: 'Тост, 1 шт',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'coleslaw',
              label: 'Коулслоу, 90 г',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'wedges',
              label: 'Картофельные дольки, 90 г',
              price_delta_minor: '89000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
          ],
        },
      ],
    },
    {
      id: 'burger-duo',
      name: 'Бургер Дуо',
      description:
        'Сытный бургер комбо с хрустящими куриными фингерсами, фирменным соусом, свежим коулслоу и мягким поджаренным тостом. 1,5 порции картофельных долек, 2 фирменных соуса, 2 напитка на выбор',
      category: 'На двоих',
      price_minor: '699000',
      image_id: 'i12.jpg',
      prep_required: true,
      serving_label: '900 г',
      ingredients:
        'Сытный бургер комбо с хрустящими куриными фингерсами, фирменным соусом, свежим коулслоу и мягким поджаренным тостом. 1,5 порции картофельных долек, 2 фирменных соуса, 2 напитка на выбор',
      allergens: [],
      prep_minutes: 9,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 2100,
        protein_g: 68,
        fat_g: 128,
        carbs_g: 168,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [
        {
          id: 'drink',
          title: 'Напитки на выбор · 2 шт',
          min: 2,
          max: 2,
          options: [
            {
              id: 'cola-bottle',
              label: 'Coca-Cola 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 2,
            },
            {
              id: 'lemonade',
              label: 'Фирменный лимонад 0.5 л',
              price_delta_minor: '20000',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'fuse-peach',
              label: 'Fuse Tea Персик 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'cola-can',
              label: 'Coca-Cola 0.5 л, банка',
              price_delta_minor: '10000',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'fanta',
              label: 'Fanta 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'sprite',
              label: 'Sprite 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'cola-zero',
              label: 'Coca-Cola Zero 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'iced-tea-sweet',
              label: 'Фирменный холодный чай, сладкий',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'iced-tea-unsweet',
              label: 'Фирменный холодный чай, несладкий',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'fuse-berry',
              label: 'Fuse Tea Ягода 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'fuse-watermelon',
              label: 'Fuse Tea Арбуз 0.5 л',
              price_delta_minor: '0',
              available: false,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'fuse-mango',
              label: 'Fuse Tea Манго-Ромашка 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'water',
              label: 'Bonaqua негазированная 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'piko',
              label: 'Piko 0.2 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'sauce',
          title: 'Соусы на выбор · 2 шт',
          min: 2,
          max: 2,
          options: [
            {
              id: 'pick',
              label: 'Фирменный соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 2,
            },
            {
              id: 'hot',
              label: 'Острый соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'cheese',
              label: 'Heinz сырный',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'bbq',
              label: 'Heinz барбекю',
              price_delta_minor: '0',
              available: false,
              max_quantity: 2,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'extras',
          title: 'Добавить к заказу',
          min: 0,
          max: 80,
          options: [
            {
              id: 'fingers',
              label: 'Фингерс, 1 шт',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce',
              label: 'Фирменный соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-hot',
              label: 'Острый соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-cheese',
              label: 'Heinz сырный, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-bbq',
              label: 'Heinz барбекю, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'toast',
              label: 'Тост, 1 шт',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'coleslaw',
              label: 'Коулслоу, 90 г',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'wedges',
              label: 'Картофельные дольки, 90 г',
              price_delta_minor: '89000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
          ],
        },
      ],
    },
    {
      id: 'mix-duo',
      name: 'Микс Дуо',
      description:
        'Сытное микс-комбо для двоих: 4 хрустящих куриных фингерса, 1,5 порции картофельных долек, 2 фирменных соуса, 1 порция свежего коулслоу, 1 фирменный тост и 2 напитка на выбор.',
      category: 'На двоих',
      price_minor: '749000',
      image_id: 'i13.jpg',
      prep_required: true,
      serving_label: '980 г',
      ingredients:
        'Сытное микс-комбо для двоих: 4 хрустящих куриных фингерса, 1,5 порции картофельных долек, 2 фирменных соуса, 1 порция свежего коулслоу, 1 фирменный тост и 2 напитка на выбор.',
      allergens: [],
      prep_minutes: 9,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 2200,
        protein_g: 82,
        fat_g: 130,
        carbs_g: 172,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [
        {
          id: 'drink',
          title: 'Напитки на выбор · 2 шт',
          min: 2,
          max: 2,
          options: [
            {
              id: 'cola-bottle',
              label: 'Coca-Cola 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 2,
            },
            {
              id: 'lemonade',
              label: 'Фирменный лимонад 0.5 л',
              price_delta_minor: '20000',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'fuse-peach',
              label: 'Fuse Tea Персик 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'cola-can',
              label: 'Coca-Cola 0.5 л, банка',
              price_delta_minor: '10000',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'fanta',
              label: 'Fanta 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'sprite',
              label: 'Sprite 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'cola-zero',
              label: 'Coca-Cola Zero 0.5 л, бутылка',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'iced-tea-sweet',
              label: 'Фирменный холодный чай, сладкий',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'iced-tea-unsweet',
              label: 'Фирменный холодный чай, несладкий',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'fuse-berry',
              label: 'Fuse Tea Ягода 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'fuse-watermelon',
              label: 'Fuse Tea Арбуз 0.5 л',
              price_delta_minor: '0',
              available: false,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'fuse-mango',
              label: 'Fuse Tea Манго-Ромашка 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'water',
              label: 'Bonaqua негазированная 0.5 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'piko',
              label: 'Piko 0.2 л',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'sauce',
          title: 'Соусы на выбор · 2 шт',
          min: 2,
          max: 2,
          options: [
            {
              id: 'pick',
              label: 'Фирменный соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 2,
            },
            {
              id: 'hot',
              label: 'Острый соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'cheese',
              label: 'Heinz сырный',
              price_delta_minor: '0',
              available: true,
              max_quantity: 2,
              default_quantity: 0,
            },
            {
              id: 'bbq',
              label: 'Heinz барбекю',
              price_delta_minor: '0',
              available: false,
              max_quantity: 2,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'extras',
          title: 'Добавить к заказу',
          min: 0,
          max: 80,
          options: [
            {
              id: 'fingers',
              label: 'Фингерс, 1 шт',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce',
              label: 'Фирменный соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-hot',
              label: 'Острый соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-cheese',
              label: 'Heinz сырный, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-bbq',
              label: 'Heinz барбекю, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'toast',
              label: 'Тост, 1 шт',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'coleslaw',
              label: 'Коулслоу, 90 г',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'wedges',
              label: 'Картофельные дольки, 90 г',
              price_delta_minor: '89000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
          ],
        },
      ],
    },
    {
      id: 'fingers-25',
      name: '25 фингерсов',
      description:
        'Большой сет для компании из 6-8 человек. 25 хрустящих куриных фингерсов и 8 фирменных соусов',
      category: 'На компанию',
      price_minor: '1399000',
      image_id: 'i14.jpg',
      prep_required: true,
      serving_label: '1900 г',
      ingredients:
        'Большой сет для компании из 6-8 человек. 25 хрустящих куриных фингерсов и 8 фирменных соусов',
      allergens: [],
      prep_minutes: 13,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 5900,
        protein_g: 300,
        fat_g: 410,
        carbs_g: 260,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [
        {
          id: 'sauce',
          title: 'Соусы на выбор · 8 шт',
          min: 8,
          max: 8,
          options: [
            {
              id: 'pick',
              label: 'Фирменный соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 8,
              default_quantity: 8,
            },
            {
              id: 'hot',
              label: 'Острый соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 8,
              default_quantity: 0,
            },
            {
              id: 'cheese',
              label: 'Heinz сырный',
              price_delta_minor: '0',
              available: true,
              max_quantity: 8,
              default_quantity: 0,
            },
            {
              id: 'bbq',
              label: 'Heinz барбекю',
              price_delta_minor: '0',
              available: false,
              max_quantity: 8,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'extras',
          title: 'Добавить к заказу',
          min: 0,
          max: 80,
          options: [
            {
              id: 'fingers',
              label: 'Фингерс, 1 шт',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce',
              label: 'Фирменный соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-hot',
              label: 'Острый соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-cheese',
              label: 'Heinz сырный, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-bbq',
              label: 'Heinz барбекю, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'toast',
              label: 'Тост, 1 шт',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'coleslaw',
              label: 'Коулслоу, 90 г',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'wedges',
              label: 'Картофельные дольки, 90 г',
              price_delta_minor: '89000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
          ],
        },
      ],
    },
    {
      id: 'fingers-50',
      name: '50 фингерсов',
      description:
        'Сет для компании из 13-15 человек. 50 хрустящих куриных фингерсов и 16 фирменных соусов',
      category: 'На компанию',
      price_minor: '2699000',
      image_id: 'i15.jpg',
      prep_required: true,
      serving_label: '3800 г',
      ingredients:
        'Сет для компании из 13-15 человек. 50 хрустящих куриных фингерсов и 16 фирменных соусов',
      allergens: [],
      prep_minutes: 13,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 11800,
        protein_g: 600,
        fat_g: 820,
        carbs_g: 520,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [
        {
          id: 'sauce',
          title: 'Соусы на выбор · 16 шт',
          min: 16,
          max: 16,
          options: [
            {
              id: 'pick',
              label: 'Фирменный соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 16,
              default_quantity: 16,
            },
            {
              id: 'hot',
              label: 'Острый соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 16,
              default_quantity: 0,
            },
            {
              id: 'cheese',
              label: 'Heinz сырный',
              price_delta_minor: '0',
              available: true,
              max_quantity: 16,
              default_quantity: 0,
            },
            {
              id: 'bbq',
              label: 'Heinz барбекю',
              price_delta_minor: '0',
              available: false,
              max_quantity: 16,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'extras',
          title: 'Добавить к заказу',
          min: 0,
          max: 80,
          options: [
            {
              id: 'fingers',
              label: 'Фингерс, 1 шт',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce',
              label: 'Фирменный соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-hot',
              label: 'Острый соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-cheese',
              label: 'Heinz сырный, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-bbq',
              label: 'Heinz барбекю, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'toast',
              label: 'Тост, 1 шт',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'coleslaw',
              label: 'Коулслоу, 90 г',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'wedges',
              label: 'Картофельные дольки, 90 г',
              price_delta_minor: '89000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
          ],
        },
      ],
    },
    {
      id: 'fingers-75',
      name: '75 фингерсов',
      description: 'Сет на 20-22 человека. 75 куриных фингерсов и 24 фирменных соуса',
      category: 'На компанию',
      price_minor: '3999000',
      image_id: 'i16.jpg',
      prep_required: true,
      serving_label: '5700 г',
      ingredients: 'Сет на 20-22 человека. 75 куриных фингерсов и 24 фирменных соуса',
      allergens: [],
      prep_minutes: 13,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 17700,
        protein_g: 900,
        fat_g: 1230,
        carbs_g: 780,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [
        {
          id: 'sauce',
          title: 'Соусы на выбор · 24 шт',
          min: 24,
          max: 24,
          options: [
            {
              id: 'pick',
              label: 'Фирменный соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 24,
              default_quantity: 24,
            },
            {
              id: 'hot',
              label: 'Острый соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 24,
              default_quantity: 0,
            },
            {
              id: 'cheese',
              label: 'Heinz сырный',
              price_delta_minor: '0',
              available: true,
              max_quantity: 24,
              default_quantity: 0,
            },
            {
              id: 'bbq',
              label: 'Heinz барбекю',
              price_delta_minor: '0',
              available: false,
              max_quantity: 24,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'extras',
          title: 'Добавить к заказу',
          min: 0,
          max: 80,
          options: [
            {
              id: 'fingers',
              label: 'Фингерс, 1 шт',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce',
              label: 'Фирменный соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-hot',
              label: 'Острый соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-cheese',
              label: 'Heinz сырный, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-bbq',
              label: 'Heinz барбекю, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'toast',
              label: 'Тост, 1 шт',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'coleslaw',
              label: 'Коулслоу, 90 г',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'wedges',
              label: 'Картофельные дольки, 90 г',
              price_delta_minor: '89000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
          ],
        },
      ],
    },
    {
      id: 'fingers-100',
      name: '100 фингерсов',
      description: 'Большой сет для компании. 100 хрустящих куриных фингерсов и 32 фирменных соуса',
      category: 'На компанию',
      price_minor: '5299000',
      image_id: 'i17.jpg',
      prep_required: true,
      serving_label: '7600 г',
      ingredients: 'Большой сет для компании. 100 хрустящих куриных фингерсов и 32 фирменных соуса',
      allergens: [],
      prep_minutes: 13,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 23600,
        protein_g: 1200,
        fat_g: 1640,
        carbs_g: 1040,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [
        {
          id: 'sauce',
          title: 'Соусы на выбор · 32 шт',
          min: 32,
          max: 32,
          options: [
            {
              id: 'pick',
              label: 'Фирменный соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 32,
              default_quantity: 32,
            },
            {
              id: 'hot',
              label: 'Острый соус Pick Chick',
              price_delta_minor: '0',
              available: true,
              max_quantity: 32,
              default_quantity: 0,
            },
            {
              id: 'cheese',
              label: 'Heinz сырный',
              price_delta_minor: '0',
              available: true,
              max_quantity: 32,
              default_quantity: 0,
            },
            {
              id: 'bbq',
              label: 'Heinz барбекю',
              price_delta_minor: '0',
              available: false,
              max_quantity: 32,
              default_quantity: 0,
            },
          ],
        },
        {
          id: 'extras',
          title: 'Добавить к заказу',
          min: 0,
          max: 80,
          options: [
            {
              id: 'fingers',
              label: 'Фингерс, 1 шт',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce',
              label: 'Фирменный соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-hot',
              label: 'Острый соус, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-cheese',
              label: 'Heinz сырный, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'sauce-bbq',
              label: 'Heinz барбекю, 60 мл',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'toast',
              label: 'Тост, 1 шт',
              price_delta_minor: '39000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'coleslaw',
              label: 'Коулслоу, 90 г',
              price_delta_minor: '69000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
            {
              id: 'wedges',
              label: 'Картофельные дольки, 90 г',
              price_delta_minor: '89000',
              available: true,
              max_quantity: 10,
              default_quantity: 0,
            },
          ],
        },
      ],
    },
    {
      id: 'fingers',
      name: 'Фингерс, 1 шт',
      description:
        'Нежное куриное филе в хрустящей панировке, обжаренное до золотистой корочки. Сочное внутри, хрустящее снаружи.',
      category: 'Допы',
      price_minor: '69000',
      image_id: 'i4.jpg',
      prep_required: true,
      serving_label: '55 г',
      ingredients:
        'Нежное куриное филе в хрустящей панировке, обжаренное до золотистой корочки. Сочное внутри, хрустящее снаружи.',
      allergens: [],
      prep_minutes: 3,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 165,
        protein_g: 12,
        fat_g: 9,
        carbs_g: 9,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [],
    },
    {
      id: 'sauce',
      name: 'Соус фирменный',
      description: 'Легендарный фирменный соус Pick Chick',
      category: 'Допы',
      price_minor: '39000',
      image_id: 'i18.jpg',
      prep_required: false,
      serving_label: '60 г',
      ingredients: 'Легендарный фирменный соус Pick Chick',
      allergens: [],
      prep_minutes: 3,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 230,
        protein_g: 1,
        fat_g: 23,
        carbs_g: 4,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [
        {
          id: 'size',
          title: 'Размер соуса',
          min: 1,
          max: 1,
          options: [
            {
              id: 'size-0',
              label: '60 мл',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 1,
              nutrition_multiplier: 1,
            },
            {
              id: 'size-1',
              label: '0,3 л',
              price_delta_minor: '80000',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
              nutrition_multiplier: 5,
            },
            {
              id: 'size-2',
              label: '0,4 л',
              price_delta_minor: '110000',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
              nutrition_multiplier: 6.7,
            },
            {
              id: 'size-3',
              label: '0,5 л',
              price_delta_minor: '140000',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
              nutrition_multiplier: 8.3,
            },
          ],
        },
      ],
    },
    {
      id: 'sauce-hot',
      name: 'Соус острый',
      description:
        'Фирменный соус Pick Chick с перцем чили - для тех, кто любит острее. 60, 180 или 300 г.',
      category: 'Допы',
      price_minor: '39000',
      image_id: 'i19.jpg',
      prep_required: false,
      serving_label: '60 г',
      ingredients:
        'Фирменный соус Pick Chick с перцем чили - для тех, кто любит острее. 60, 180 или 300 г.',
      allergens: [],
      prep_minutes: 3,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 220,
        protein_g: 1,
        fat_g: 21,
        carbs_g: 5,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [
        {
          id: 'size',
          title: 'Размер соуса',
          min: 1,
          max: 1,
          options: [
            {
              id: 'size-0',
              label: '60 мл',
              price_delta_minor: '0',
              available: true,
              max_quantity: 1,
              default_quantity: 1,
              nutrition_multiplier: 1,
            },
            {
              id: 'size-1',
              label: '0,3 л',
              price_delta_minor: '80000',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
              nutrition_multiplier: 5,
            },
            {
              id: 'size-2',
              label: '0,4 л',
              price_delta_minor: '110000',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
              nutrition_multiplier: 6.7,
            },
            {
              id: 'size-3',
              label: '0,5 л',
              price_delta_minor: '140000',
              available: true,
              max_quantity: 1,
              default_quantity: 0,
              nutrition_multiplier: 8.3,
            },
          ],
        },
      ],
    },
    {
      id: 'toast',
      name: 'Тост, 1 шт',
      description: 'Фирменный тост с хрустящей золотистой корочкой, пропитанный чесночным маслом.',
      category: 'Допы',
      price_minor: '39000',
      image_id: 'i5.jpg',
      prep_required: true,
      serving_label: '40 г',
      ingredients: 'Фирменный тост с хрустящей золотистой корочкой, пропитанный чесночным маслом.',
      allergens: [],
      prep_minutes: 3,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 150,
        protein_g: 4,
        fat_g: 7,
        carbs_g: 18,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [],
    },
    {
      id: 'coleslaw',
      name: 'Коулслоу, 90 г',
      description:
        'Свежий салат из белокочанной и краснокочанной капусты с морковью, заправленный фирменным соусом.',
      category: 'Допы',
      price_minor: '69000',
      image_id: 'i6.jpg',
      prep_required: true,
      serving_label: '90 г',
      ingredients:
        'Свежий салат из белокочанной и краснокочанной капусты с морковью, заправленный фирменным соусом.',
      allergens: [],
      prep_minutes: 3,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 120,
        protein_g: 1,
        fat_g: 9,
        carbs_g: 7,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [],
    },
    {
      id: 'wedges',
      name: 'Картофельные дольки, 90 г',
      description: 'Хрустящие картофельные дольки с золотистой корочкой.',
      category: 'Допы',
      price_minor: '89000',
      image_id: 'i20.jpg',
      prep_required: true,
      serving_label: '90 г',
      ingredients: 'Хрустящие картофельные дольки с золотистой корочкой.',
      allergens: [],
      prep_minutes: 3,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 210,
        protein_g: 3,
        fat_g: 11,
        carbs_g: 25,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [],
    },
    {
      id: 'burger',
      name: 'Бургер, 1 шт',
      description:
        'Сочный бургер с хрустящими куриными фингерсами, свежим коулслоу, фирменным соусом и мягкой булочкой бриошь.',
      category: 'Допы',
      price_minor: '239000',
      image_id: 'shot.jpg',
      prep_required: true,
      serving_label: '240 г',
      ingredients:
        'Сочный бургер с хрустящими куриными фингерсами, свежим коулслоу, фирменным соусом и мягкой булочкой бриошь.',
      allergens: [],
      prep_minutes: 3,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 620,
        protein_g: 28,
        fat_g: 33,
        carbs_g: 52,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [],
    },
    {
      id: 'lemonade',
      name: 'Фирменный лимонад 0.5 л',
      description:
        'Натуральный лимонад собственного приготовления из свежих апельсинов, лимонов, сахара и воды. Освежающий вкус без лишних добавок.',
      category: 'Напитки',
      price_minor: '119000',
      image_id: 'i0.jpg',
      prep_required: false,
      serving_label: '500 мл',
      ingredients:
        'Натуральный лимонад собственного приготовления из свежих апельсинов, лимонов, сахара и воды. Освежающий вкус без лишних добавок.',
      allergens: [],
      prep_minutes: 1,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 210,
        protein_g: 0,
        fat_g: 0,
        carbs_g: 52,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [],
    },
    {
      id: 'cola',
      name: 'Coca-Cola 0.5 л, банка',
      description: 'Coca-Cola Classic в железной банке, 0,5 л.',
      category: 'Напитки',
      price_minor: '99000',
      image_id: 'i2.jpg',
      prep_required: false,
      serving_label: '500 мл',
      ingredients: 'Coca-Cola Classic в железной банке, 0,5 л.',
      allergens: [],
      prep_minutes: 1,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 210,
        protein_g: 0,
        fat_g: 0,
        carbs_g: 53,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [],
    },
    {
      id: 'fuse-peach',
      name: 'Fuse Tea Персик 0.5 л',
      description: 'Холодный чай Fuse Tea со вкусом персика, 0,5 л.',
      category: 'Напитки',
      price_minor: '79000',
      image_id: 'i1.jpg',
      prep_required: false,
      serving_label: '500 мл',
      ingredients: 'Холодный чай Fuse Tea со вкусом персика, 0,5 л.',
      allergens: [],
      prep_minutes: 1,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 90,
        protein_g: 0,
        fat_g: 0,
        carbs_g: 22,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [],
    },
    {
      id: 'iced-tea',
      name: 'Холодный чай 0.5 л',
      description:
        'Освежающий холодный чай собственного приготовления. Есть сладкий и не сладкий, можно миксовать',
      category: 'Напитки',
      price_minor: '49000',
      image_id: 'i22.jpg',
      prep_required: false,
      serving_label: '500 мл',
      ingredients:
        'Освежающий холодный чай собственного приготовления. Есть сладкий и не сладкий, можно миксовать',
      allergens: [],
      prep_minutes: 1,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 110,
        protein_g: 0,
        fat_g: 0,
        carbs_g: 27,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [],
    },
    {
      id: 'water',
      name: 'Bonaqua негаз. 0.5 л',
      description: 'Питьевая вода без газа, 0,5 л.',
      category: 'Напитки',
      price_minor: '59000',
      image_id: 'i23.jpg',
      prep_required: false,
      serving_label: '500 мл',
      ingredients: 'Питьевая вода без газа, 0,5 л.',
      allergens: [],
      prep_minutes: 1,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 0,
        protein_g: 0,
        fat_g: 0,
        carbs_g: 0,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [],
    },
    {
      id: 'piko',
      name: 'Piko 0.2 л',
      description: 'Трубочный напиток Piko, 0,2 л.',
      category: 'Напитки',
      price_minor: '59000',
      image_id: 'generic-drink',
      prep_required: false,
      serving_label: '200 мл',
      ingredients: 'Трубочный напиток Piko, 0,2 л.',
      allergens: [],
      prep_minutes: 1,
      nutrition: {
        basis: 'per_serving',
        energy_kcal: 90,
        protein_g: 1,
        fat_g: 0,
        carbs_g: 22,
      },
      nutrition_provenance: 'source_mockup',
      modifier_groups: [],
    },
  ],
  estimated_minutes: {
    min: 1,
    max: 13,
  },
  upsell_product_ids: ['sauce', 'toast', 'wedges', 'fuse-peach'],
});
