import { StyleSheet } from 'react-native';
import { font } from '../../theme';
export const sortColors = {
  background: '#515B5C',
  ink: '#FCF4E3',
  muted: '#D3DCDB',
  surface: '#3D484A',
  accent: '#EDBB47',
  yellow: '#E6B91B',
  ivory: '#EEEFE9',
  taupe: '#AC9C87',
  orange: '#D88B50',
  rose: '#A46C79',
  wine: '#591F29',
};
export const sortStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: sortColors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 12,
  },
  title: { fontFamily: font.display, fontSize: 22, color: sortColors.ink },
  caption: { fontFamily: font.medium, fontSize: 12, color: sortColors.muted },
  stats: { flexDirection: 'row', gap: 12 },
  iconButton: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: sortColors.surface,
  },
  pressed: { opacity: 0.7 },
  notice: {
    fontFamily: font.medium,
    fontSize: 12,
    lineHeight: 17,
    color: sortColors.ink,
    textAlign: 'center',
  },
  dock: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 12,
  },
  action: {
    minHeight: 48,
    flex: 1,
    maxWidth: 150,
    borderRadius: 14,
    gap: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: sortColors.surface,
    paddingHorizontal: 5,
  },
  actionLabel: { fontFamily: font.bold, fontSize: 11, color: sortColors.ink },
  disabled: { opacity: 0.4 },
  overlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#172426DD',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  panel: {
    width: '100%',
    maxWidth: 430,
    backgroundColor: '#F8F0DC',
    padding: 22,
    borderRadius: 22,
    gap: 16,
  },
  panelTitle: { fontFamily: font.heading, fontSize: 24, color: '#273B3E' },
  body: { fontFamily: font.body, fontSize: 14, lineHeight: 22, color: '#273B3E' },
  panelButton: {
    minHeight: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    backgroundColor: '#E7DDC7',
  },
  panelButtonLabel: { fontFamily: font.bold, fontSize: 14, color: '#273B3E' },
  primaryButton: { backgroundColor: sortColors.accent },
  resultRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 10 },
  resultLabel: { fontFamily: font.bold, fontSize: 16, color: '#273B3E' },
  badge: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 5,
    backgroundColor: sortColors.accent,
  },
  badgeLabel: { fontFamily: font.bold, fontSize: 13, color: '#273B3E' },
});
