"""Synthetic accounting acceptance against real HTTP/PostgreSQL, never the restaurant."""
import json
import re
import sys
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

c = json.loads(Path(sys.argv[1]).read_text())
out = Path(c['output'])
with sync_playwright() as pw:
    browser = pw.chromium.launch()
    page = browser.new_page(viewport={'width': 1440, 'height': 960})
    page.set_default_timeout(15000)
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.on('dialog', lambda d: d.accept())
    page.goto(c['url'] + '#finance')
    page.get_by_test_id('credential-file').set_input_files({
        'name': 'synthetic.json', 'mimeType': 'application/json',
        'buffer': json.dumps(c['manager']).encode(),
    })
    def b(label):
        return page.get_by_role('button', name=label, exact=True)
    def tab(label):
        b(label).click()
    def period(start, end):
        page.get_by_test_id('finance-start').fill(start)
        page.get_by_test_id('finance-end').fill(end)
        b('Показать').click()
        expect(b('Показать')).to_be_enabled()
    expect(b('Настройки')).to_be_enabled()
    period('2026-10-01', '2026-10-31')
    expect(page.get_by_role('heading', name='Финансы за период')).to_be_visible()
    b('Добавить операцию').click()
    expect(page.get_by_test_id('finance-account')).to_have_count(0)
    expect(page.get_by_test_id('finance-to-account')).to_have_count(0)
    for width, height in [(1440, 960), (393, 852)]:
        page.set_viewport_size({'width': width, 'height': height})
        assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'), width
        page.screenshot(path=str(out / f'finance-entry-{width}.png'), full_page=True)
    page.set_viewport_size({'width': 1440, 'height': 960})
    page.get_by_text('Дополнительно: ОПиУ, контрагент, примечание', exact=True).click()
    page.get_by_test_id('finance-amount').fill('500,25')
    page.get_by_test_id('finance-cash-date').fill('2026-10-06')
    page.get_by_test_id('finance-recognition-date').fill('2026-09-30')
    page.get_by_test_id('finance-category').select_option('utilities')
    page.get_by_test_id('finance-entry-center').select_option('workshop')
    page.get_by_test_id('finance-counterparty').fill('Синтетический поставщик')
    page.get_by_test_id('finance-reference').fill('Синтетические коммунальные услуги')
    page.get_by_test_id('finance-note').fill('<img src=x onerror=alert(1)>')
    # Commit once, lose the reply, reload, then recover the identical request.
    requests = []
    def lose_reply(route):
        requests.append(route.request.post_data_json)
        response = route.fetch()
        assert response.status == 200
        route.abort('failed')
    route = '**/v1/admin/backoffice/branches/*/finance/commands'
    page.route(route, lose_reply)
    b('Провести операцию').click()
    expect(b('Проверить результат')).to_be_enabled()
    page.unroute(route, lose_reply)
    page.reload()
    expect(b('Проверить результат')).to_be_enabled()
    recovered = []
    page.on('request', lambda r: recovered.append(r.post_data_json) if r.method == 'POST' else None)
    b('Проверить результат').click()
    expect(b('Проверить результат')).to_have_count(0)
    assert recovered[0] == requests[0]
    assert requests[0]['command']['entry']['account_id'] is None
    tab('Журнал операций')
    expect(b('Синтетические коммунальные услуги')).to_have_count(1)
    tab('ДДС')
    expect(page.locator('.finance-totals')).to_contain_text('500,25 ₸')
    page.get_by_text('Точные значения по датам', exact=True).click()
    expect(page.locator('.finance-chart-data')).to_contain_text('500,25 ₸')
    expect(page.locator('.finance-ranking')).to_contain_text('100,0%')
    tab('ОПиУ')
    expect(page.locator('.finance-totals')).not_to_contain_text('500,25')
    period('2026-09-01', '2026-09-30')
    expect(page.locator('.finance-totals')).to_contain_text('-500,25 ₸')
    page.get_by_text('Аренда и коммунальные услуги', exact=True).click()
    page.locator('.finance-sheet summary').filter(has_text=re.compile(r'^Коммунальные услуги$')).click()
    page.locator('details[open] > .finance-link').filter(has_text='Показать операции').click()
    expect(page.get_by_test_id('finance-filter-basis')).to_have_value('pnl')
    expect(b('Синтетические коммунальные услуги')).to_be_visible()
    b('Синтетические коммунальные услуги').click()
    assert page.locator('img[src=x]').count() == 0
    expect(page.locator('.finance-editor')).to_contain_text('2026-09-30')
    b('К журналу').click()
    tab('ОПиУ')
    with page.expect_download() as download:
        b('Скачать отчёт CSV').click()
    saved = download.value.path()
    assert 'Коммунальные услуги' in Path(saved).read_text(encoding='utf-8-sig')
    for width, height in [(1440, 960), (768, 1024), (393, 852)]:
        page.set_viewport_size({'width': width, 'height': height})
        assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'), width
        page.screenshot(path=str(out / f'finance-pnl-{width}.png'), full_page=True)
    tab('Журнал операций')
    page.get_by_test_id('finance-search').fill('несуществующий контрагент')
    b('Найти').click()
    expect(page.locator('.content')).to_contain_text('За выбранный период записей нет.')
    page.get_by_test_id('finance-search').fill('поставщик')
    b('Найти').click()
    expect(b('Синтетические коммунальные услуги')).to_be_visible()
    tab('Настройки')
    page.get_by_test_id('finance-period-month').fill('2026-09')
    page.get_by_label('Причина закрытия / открытия', exact=True).fill('Синтетическая проверка месяца')
    b('Закрыть месяц').click()
    expect(page.locator('.content')).to_contain_text('Статус 2026-09: закрыт')
    tab('Журнал операций')
    b('Синтетические коммунальные услуги').click()
    b('Удалить').click()
    page.get_by_label('Причина удаления', exact=True).fill('Синтетическая ошибочная запись')
    b('Подтвердить удаление').click()
    expect(page.locator('[role=alert]')).to_contain_text('месяц закрыт')
    expect(page.get_by_label('Причина удаления', exact=True)).to_have_value('Синтетическая ошибочная запись')
    b('К журналу').click()
    tab('Настройки')
    page.get_by_label('Причина закрытия / открытия', exact=True).fill('Синтетическое исправление')
    b('Открыть для исправлений').click()
    expect(page.locator('.content')).to_contain_text('Статус 2026-09: открыт')
    tab('Журнал операций')
    b('Синтетические коммунальные услуги').click()
    b('Удалить').click()
    b('Не удалять').click()
    expect(b('Подтвердить удаление')).to_have_count(0)
    b('Изменить').click()
    expect(page.get_by_test_id('finance-amount')).to_have_value('500.25')
    expect(page.get_by_test_id('finance-recognition-date')).to_have_value('2026-09-30')
    expect(page.get_by_test_id('finance-cash-date')).to_have_value('2026-10-06')
    page.get_by_test_id('finance-amount').fill('650.75')
    page.get_by_test_id('finance-reference').fill('Исправленные коммунальные услуги')
    page.get_by_test_id('finance-edit-reason').fill('Уточнена сумма по документу')
    page.route(route, lose_reply)
    b('Сохранить изменения').click()
    expect(b('Проверить результат')).to_be_enabled()
    page.unroute(route, lose_reply)
    b('Проверить результат').click()
    expect(b('Проверить результат')).to_have_count(0)
    expect(b('Сохранить изменения')).to_have_count(0)
    expect(b('Исправленные коммунальные услуги')).to_be_visible()
    tab('ОПиУ')
    expect(page.locator('.finance-totals')).to_contain_text('650,75')
    expect(page.locator('.finance-totals')).not_to_contain_text('500,25')
    tab('Журнал операций')
    b('Синтетические коммунальные услуги').click()
    expect(page.locator('.finance-entry-status')).to_have_text('Изменена')
    b('Открыть последнюю версию').click()
    expect(page.locator('.finance-history')).to_contain_text('Уточнена сумма по документу')
    expect(page.locator('.finance-history')).to_contain_text('500,25')
    expect(page.locator('.finance-history')).to_contain_text('650,75')
    for width, height in [(1440, 960), (768, 1024), (393, 852)]:
        page.set_viewport_size({'width': width, 'height': height})
        assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'), width
        page.screenshot(path=str(out / f'finance-history-{width}.png'), full_page=True)
    b('Удалить').click()
    page.get_by_label('Причина удаления', exact=True).fill('Повторный документ удалён')
    b('Подтвердить удаление').click()
    expect(page.locator('.content')).to_contain_text('Удалена')
    expect(page.locator('.finance-history')).to_contain_text('Операция удалена')
    expect(page.locator('.finance-history')).to_contain_text('Повторный документ удалён')
    expect(b('Изменить')).to_have_count(0)
    expect(b('Удалить')).to_have_count(0)
    tab('ОПиУ')
    expect(page.locator('.finance-totals')).not_to_contain_text('650,75')
    assert errors == [], errors
    browser.close()
print('PASS: real finance save/replay, recognition periods, search, CSV, closed month, edit/replay, visible audit, delete confirmation, 3 widths')
