import sys
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page(viewport={"width":1440,"height":1000}, device_scale_factor=1, locale="ru-RU")
    errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto(sys.argv[1])
    expect(page.get_by_role('heading', name='Смены и команда')).to_be_visible()
    expect(page.get_by_text('Тестовый повар',exact=True).last).to_be_visible()
    page.screenshot(path='.local/workforce-ui/plan-1440.png',full_page=True)
    page.get_by_role('button',name='Сотрудники',exact=True).click()
    page.get_by_role('button',name='Добавить сотрудника',exact=True).click()
    page.get_by_label('Имя сотрудника').fill('Тестовый новый сотрудник')
    page.get_by_label('Причина добавления или изменения').fill('Добавляем в команду для проверки')
    page.get_by_role('button',name='Сохранить',exact=True).click()
    expect(page.get_by_role('heading',name='Почасовые ставки')).to_be_visible()
    expect(page.get_by_role('cell',name='Тестовый новый сотрудник',exact=True)).to_be_visible()
    page.get_by_role('button',name='Табель',exact=True).click()
    page.get_by_role('button',name='Внести явку',exact=True).click()
    page.get_by_label('Дата явки').fill('2026-09-02')
    page.get_by_label('Оплачиваемые интервалы').fill('09:00-12:00\n12:30-17:00')
    page.get_by_label('Подтверждение',exact=True).select_option('approved')
    page.get_by_label('Примечание / основание явки').fill('Сверено с журналом')
    page.get_by_label('Причина добавления или изменения').fill('Ручная явка до подключения BioCheck')
    page.screenshot(path='.local/workforce-ui/editor-1440.png',full_page=True)
    page.get_by_role('button',name='Сохранить',exact=True).click()
    expect(page.get_by_role('cell',name='02.09.2026',exact=True)).to_be_visible()
    row=page.get_by_role('row').filter(has=page.get_by_role('cell',name='02.09.2026',exact=True))
    row.get_by_role('button',name='Изменить').click()
    page.get_by_label('Подтверждение',exact=True).select_option('voided')
    page.get_by_label('Причина добавления или изменения').fill('Ошибочная явка, аннулируем с историей')
    page.get_by_role('button',name='Сохранить',exact=True).click()
    expect(page.get_by_role('cell',name='Аннулировано',exact=True)).to_be_visible()
    page.get_by_role('button',name='Начисления',exact=True).click()
    expect(page.get_by_role('heading',name='Предварительные начисления')).to_be_visible()
    page.screenshot(path='.local/workforce-ui/pay-1440.png',full_page=True)
    page.locator('.wf-toolbar select').select_option(label='Тестовый новый сотрудник')
    expect(page.locator('.wf-summary')).to_contain_text('0,00 ₸')
    expect(page.locator('.wf-summary')).to_contain_text('0 ч 0 мин')
    page.screenshot(path='.local/workforce-ui/pay-filter-1440.png',full_page=True)
    page.locator('.wf-toolbar select').select_option('')

    with page.expect_download() as download:
        page.get_by_role('button',name='Скачать CSV',exact=True).click()
    assert download.value.suggested_filename.endswith('.csv')
    assert 'Предварительный расчёт' in Path(download.value.path()).read_text(encoding='utf-8-sig')
    page.get_by_role('button',name='История',exact=True).click()
    expect(page.get_by_role('cell',name='Ошибочная явка, аннулируем с историей')).to_be_visible()
    page.get_by_role('button',name='Начисления',exact=True).click()
    page.set_viewport_size({'width':393,'height':852})
    page.screenshot(path='.local/workforce-ui/pay-393.png',full_page=True)
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'), 'Page overflows on mobile'
    page.get_by_role('button',name='График',exact=True).click()
    page.screenshot(path='.local/workforce-ui/plan-393.png',full_page=True)
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'), 'Schedule overflows on mobile'

    page.get_by_role('button',name='Неделя',exact=True).click()
    page.get_by_label('Дата',exact=True).fill('2026-10-01')
    expect(page.get_by_label('Месяц',exact=True)).to_have_value('2026-10')
    expect(page.get_by_label('Дата',exact=True)).to_have_value('2026-10-01')
    expect(page.get_by_role('cell',name='30.09.2026',exact=True)).to_be_visible()
    expect(page.get_by_role('cell',name='01.10.2026',exact=True)).to_be_visible()
    page.screenshot(path='.local/workforce-ui/boundary-week-393.png',full_page=True)
    assert not errors, errors
    browser.close()
print('Workforce browser: employee, manual attendance, void with audit, CSV, desktop/mobile passed')
