import sys,json
from playwright.sync_api import sync_playwright,expect
credential=sys.stdin.read()
with sync_playwright() as p:
 browser=p.chromium.launch()
 page=browser.new_page(viewport={'width':1440,'height':1000},locale='ru-RU')
 errors=[]
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.goto(sys.argv[1]+'/#shifts')
 page.get_by_test_id('credential-file').set_input_files({'name':'synthetic.json','mimeType':'application/json','buffer':credential.encode()})
 expect(page.get_by_role('heading',name='Смены и команда')).to_be_visible()
 page.get_by_label('Месяц',exact=True).fill('2026-10')
 page.get_by_role('button',name='Сотрудники',exact=True).click()
 page.get_by_role('button',name='Добавить сотрудника',exact=True).click()
 page.get_by_label('Имя сотрудника').fill('Синтетический сотрудник')
 page.get_by_label('Причина добавления или изменения').fill('Проверка через настоящий API')
 page.get_by_role('button',name='Сохранить',exact=True).click()
 expect(page.get_by_role('cell',name='Синтетический сотрудник',exact=True)).to_be_visible()
 page.get_by_role('button',name='Табель',exact=True).click()
 page.get_by_role('button',name='Внести явку',exact=True).click()
 page.get_by_label('Дата явки').fill('2026-10-01')
 page.get_by_label('Оплачиваемые интервалы').fill('09:00-17:00')
 page.get_by_label('Подтверждение',exact=True).select_option('approved')
 page.get_by_label('Примечание / основание явки').fill('Синтетическая проверка')
 page.get_by_label('Причина добавления или изменения').fill('Проверка полного пути сохранения')
 page.once('dialog',lambda d:d.dismiss())
 page.get_by_test_id('nav-finance').click()
 expect(page.get_by_label('Оплачиваемые интервалы')).to_have_value('09:00-17:00')
 page.get_by_role('button',name='Сохранить',exact=True).click()
 expect(page.get_by_role('cell',name='01.10.2026',exact=True)).to_be_visible()
 page.screenshot(path='.local/workforce-ui/shell-timesheet-1440.png',full_page=True)
 page.reload()
 expect(page.get_by_role('heading',name='Смены и команда')).to_be_visible()
 page.get_by_label('Месяц',exact=True).fill('2026-10')
 page.get_by_role('button',name='Табель',exact=True).click()
 expect(page.get_by_role('cell',name='01.10.2026',exact=True)).to_be_visible()
 page.set_viewport_size({'width':393,'height':852})
 page.screenshot(path='.local/workforce-ui/shell-timesheet-393.png',full_page=True)
 assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'),'Shell overflow'
 assert not errors,errors
 browser.close()
print('Full shell/API/proxy: login, employee, attendance, dirty guard, persisted reload and mobile passed')
