// Reviewed local menu photographs. Requests cannot choose filesystem paths.
export const MENU_ASSETS = Object.freeze([
  'i0.jpg',
  'i1.jpg',
  'i10.jpg',
  'i11.jpg',
  'i12.jpg',
  'i13.jpg',
  'i14.jpg',
  'i15.jpg',
  'i16.jpg',
  'i17.jpg',
  'i18.jpg',
  'i19.jpg',
  'i2.jpg',
  'i20.jpg',
  'i22.jpg',
  'i23.jpg',
  'i4.jpg',
  'i5.jpg',
  'i6.jpg',
  'i7.jpg',
  'i8.jpg',
  'i9.jpg',
  'shot.jpg',
]);
