export const V2_ASSETS = [
  ['v2/photos.js', 'text/javascript'],
  ['v2/assets/menu-00.png', 'image/png'],
  ['v2/assets/menu-01.png', 'image/png'],
  ['v2/assets/menu-02.png', 'image/png'],
  ['v2/assets/menu-03.png', 'image/png'],
  ['v2/assets/menu-04.png', 'image/png'],
  ['v2/assets/menu-05.png', 'image/png'],
  ['v2/assets/menu-06.png', 'image/png'],
  ['v2/assets/menu-07.png', 'image/png'],
  ['v2/assets/menu-08.png', 'image/png'],
  ['v2/assets/menu-09.png', 'image/png'],
  ['v2/assets/menu-10.png', 'image/png'],
  ['v2/assets/menu-11.png', 'image/png'],
  ['v2/assets/menu-12.png', 'image/png'],
  ['v2/assets/menu-13.jpg', 'image/jpeg'],
  ['v2/assets/menu-14.png', 'image/png'],
  ['v2/assets/menu-15.png', 'image/png'],
  ['v2/assets/menu-16.png', 'image/png'],
  ['v2/assets/menu-17.png', 'image/png'],
  ['v2/assets/menu-18.png', 'image/png'],
  ['v2/assets/menu-19.png', 'image/png'],
  ['v2/assets/menu-20.png', 'image/png'],
  ['v2/assets/menu-21.png', 'image/png'],
  ['v2/assets/menu-22.png', 'image/png'],
  ['v2/app.js', 'text/javascript'],
  ['v2/pin-login.js', 'text/javascript'],
  ['v2/runtime.js', 'text/javascript'],
  ['v2/reference-view.js', 'text/javascript'],
  ['v2/template-engine.js', 'text/javascript'],
  ['v2/template.html', 'text/html; charset=utf-8'],
  ['v2/styles.css', 'text/css'],
  ['v2/assets/bg-blue.png', 'image/png'],
  ['v2/assets/logo.png', 'image/png'],
  ['v2/assets/kaspi.png', 'image/png'],
  ...[
    'golos-text-2f175b8fc40e.woff2',
    'golos-text-f8d71091110f.woff2',
    'montserrat-6438d7b8ea9c.woff2',
    'montserrat-0b00fbd6edcc.woff2',
  ].map((n) => ['v2/fonts/' + n, 'font/woff2']),
];
