"""Read existing sprite alpha; emit hit masks without editing artwork. Requires Pillow."""
from pathlib import Path
import hashlib
from PIL import Image

root = Path(__file__).resolve().parent
assets = root.parents[2] / 'assets/games/pick-farm'
size = 128
items = []
for atlas, boxes in [
    ('props-painted-v2.png', {'soil': (741, 235, 1429, 623), 'sprouts': (1473, 235, 2157, 622)}),
    ('plants-painted-v2.png', {
        f'{crop}-{phase}': (column * 256 + 4, row * (1024 / 3) + 3, column * 256 + 252, (row + 1) * (1024 / 3) - 3)
        for column, crop in enumerate(['carrot', 'tomato', 'strawberry', 'sunflower', 'tulip', 'apple'])
        for row, phase in enumerate(['growing', 'ready', 'withered'])
    }),
]:
    source = assets / atlas
    image = Image.open(source).convert('RGBA')
    for key, (left, top, right, bottom) in boxes.items():
        rows = []
        for y in range(size):
            bits = 0
            for x in range(size):
                px = int(left + (x + .5) / size * (right - left))
                py = int(top + (y + .5) / size * (bottom - top))
                bits = (bits << 1) | int(image.getpixel((px, py))[3] >= 48)
            rows.append(f'{bits:032x}')
        items.append(f"  '{key}': '" + '/'.join(rows) + "',")
text = '// Generated by build-hit-masks.py from existing PNG alpha (128x128, alpha >= 48).\n'
for name in ['props-painted-v2.png', 'plants-painted-v2.png']:
    text += f'// {name}: {hashlib.sha256((assets / name).read_bytes()).hexdigest()}\n'
text += 'export const spriteHitMasks: Record<string, string> = {\n' + '\n'.join(items) + '\n};\n'
(root / 'sprite-hit-masks.ts').write_text(text)
