import { StyleSheet } from 'react-native';
import { font } from '../../theme';
export const farmPalette = {
  ink: '#18332C',
  muted: '#506253',
  paper: '#FFF9EA',
  field: '#8FC34D',
  blue: '#0047BB',
  orange: '#FF6900',
  border: '#D5DBC6',
  green: '#317247',
};
export const farmStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: farmPalette.field, overflow: 'hidden' },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, gap: 14 },
  title: { fontFamily: font.display, fontSize: 23, color: farmPalette.ink },
  text: { fontFamily: font.body, fontSize: 14, color: farmPalette.ink, lineHeight: 21 },
  muted: { fontFamily: font.medium, fontSize: 12, color: farmPalette.muted },
  hud: { position: 'absolute', flexDirection: 'row', alignItems: 'center', gap: 10 },
  pill: {
    backgroundColor: farmPalette.paper,
    borderRadius: 16,
    paddingHorizontal: 14,
    minHeight: 48,
    justifyContent: 'center',
    shadowColor: '#365932',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.13,
    shadowRadius: 9,
    elevation: 3,
  },
  metric: { fontFamily: font.bold, fontSize: 17, color: farmPalette.ink },
  button: {
    minHeight: 48,
    minWidth: 48,
    borderRadius: 14,
    backgroundColor: farmPalette.paper,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    flexDirection: 'row',
    gap: 8,
  },
  primary: { backgroundColor: farmPalette.blue },
  buttonText: { fontFamily: font.bold, fontSize: 14, color: farmPalette.ink },
  primaryText: { color: '#FFFFFF' },
  pressed: { opacity: 0.75 },
  disabled: { opacity: 0.48 },
  bottomBar: { position: 'absolute', flexDirection: 'row', alignItems: 'center', gap: 8 },
  panel: {
    position: 'absolute',
    backgroundColor: farmPalette.paper,
    borderRadius: 20,
    shadowColor: '#203B27',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 8,
    padding: 16,
  },
  panelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  panelTitle: { fontFamily: font.heading, fontSize: 20, color: farmPalette.ink },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  choice: { backgroundColor: '#F0EAD8', borderRadius: 14, padding: 12, gap: 5, width: 132 },
  choiceName: { fontFamily: font.bold, fontSize: 14, color: farmPalette.ink },
  separator: { height: 1, backgroundColor: farmPalette.border, marginVertical: 12 },
  error: {
    position: 'absolute',
    backgroundColor: '#FFF1EC',
    padding: 10,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  errorText: { fontFamily: font.medium, color: '#91351D', fontSize: 13, flex: 1 },
  plot: {
    position: 'absolute',
    width: 86,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selection: {
    position: 'absolute',
    width: 64,
    height: 64,
    borderRadius: 10,
    borderColor: '#FFF9EA',
    borderWidth: 3,
    transform: [{ rotate: '45deg' }, { scaleY: 0.5 }],
  },
  ready: {
    position: 'absolute',
    right: 4,
    top: -7,
    backgroundColor: farmPalette.blue,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  time: {
    position: 'absolute',
    bottom: 0,
    backgroundColor: farmPalette.paper,
    borderRadius: 8,
    paddingHorizontal: 5,
    fontFamily: font.bold,
    fontSize: 10,
    color: farmPalette.ink,
  },
  emptyPlot: { color: '#694B31', fontFamily: font.heading, fontSize: 24 },
});
